# Copyright (C) 2026 Vertel Sverige AB (<https://vertel.se>).
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{
    "name": "Vertel Dashboard — BI Platform",
    "version": "18.0.1.0.0",
    "category": "Reporting",
    "summary": "Enterprise BI dashboard platform with semantic metrics, alerting, and cross-chart interactivity",
    "author": "Vertel Sverige AB",
    "website": "https://vertel.se",
    "license": "AGPL-3",
    "depends": ["web", "mail", "base"],
    "external_dependencies": {},
    "data": [
        "security/dashboard_security.xml",
        "security/ir.model.access.csv",
        "data/dashboard_source_data.xml",
        "data/dashboard_cron.xml",
        "views/dashboard_views.xml",
        "views/dashboard_chart_views.xml",
        "views/dashboard_metric_views.xml",
        "views/dashboard_filter_views.xml",
        "views/dashboard_alert_views.xml",
        "views/dashboard_menus.xml",
        "views/dashboard_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "dashboard_vrtl/static/src/lib/amcharts/index.js",
            "dashboard_vrtl/static/src/lib/amcharts/xy.js",
            "dashboard_vrtl/static/src/lib/amcharts/percent.js",
            "dashboard_vrtl/static/src/lib/amcharts/radar.js",
            "dashboard_vrtl/static/src/lib/amcharts/flow.js",
            "dashboard_vrtl/static/src/lib/amcharts/hierarchy.js",
            "dashboard_vrtl/static/src/lib/amcharts/map.js",
            "dashboard_vrtl/static/src/lib/amcharts/worldLow.js",
            "dashboard_vrtl/static/src/lib/amcharts/exporting.js",
            "dashboard_vrtl/static/src/lib/themes/themes.js",
            "dashboard_vrtl/static/src/lib/gridstack/gridstack.min.css",
            "dashboard_vrtl/static/src/js/*.js",
            "dashboard_vrtl/static/src/components/**/*",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
